In [ ]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

####Data Exploration

In [ ]:
transaction_data = pd.read_csv('/content/drive/MyDrive/Case Studies/HSBC/datasets/bank_transactions.csv')

In [ ]:
df = transaction_data.copy()
df

,TransactionID,CustomerID,CustomerDOB,CustGender,CustLocation,CustAccountBalance,TransactionDate,TransactionTime,TransactionAmount (INR)
0,T1,C5841053,10/1/94,F,JAMSHEDPUR,17819.05,2/8/16,143207,25.0
1,T2,C2142763,4/4/57,M,JHAJJAR,2270.69,2/8/16,141858,27999.0
2,T3,C4417068,26/11/96,F,MUMBAI,17874.44,2/8/16,142712,459.0
3,T4,C5342380,14/9/73,F,MUMBAI,866503.21,2/8/16,142714,2060.0
4,T5,C9031234,24/3/88,F,NAVI MUMBAI,6714.43,2/8/16,181156,1762.5
...,...,...,...,...,...,...,...,...,...
1048562,T1048563,C8020229,8/4/90,M,NEW DELHI,7635.19,18/9/16,184824,799.0
1048563,T1048564,C6459278,20/2/92,M,NASHIK,27311.42,18/9/16,183734,460.0
1048564,T1048565,C6412354,18/5/89,M,HYDERABAD,221757.06,18/9/16,183313,770.0
1048565,T1048566,C6420483,30/8/78,M,VISAKHAPATNAM,10117.87,18/9/16,184706,1000.0
1048566,T1048567,C8337524,5/3/84,M,PUNE,75734.42,18/9/16,181222,1166.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048567 entries, 0 to 1048566
Data columns (total 9 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   TransactionID            1048567 non-null  object
 1   CustomerID               1048567 non-null  object
 2   CustomerDOB              1045170 non-null  object
 3   CustGender               1047467 non-null  object
 4   CustLocation             1048416 non-null  object
 5   CustAccountBalance       1046198 non-null  float64
 6   TransactionDate          1048567 non-null  object
 7   TransactionTime          1048567 non-null  int64
 8   TransactionAmount (INR)  1048567 non-null  float64
dtypes: float64(2), int64(1), object(6)
memory usage: 72.0+ MB

In [ ]:
df.isna().sum()

TransactionID                 0
CustomerID                    0
CustomerDOB                3397
CustGender                 1100
CustLocation                151
CustAccountBalance         2369
TransactionDate               0
TransactionTime               0
TransactionAmount (INR)       0
dtype: int64

In [ ]:
df.describe()

       CustAccountBalance  TransactionTime  TransactionAmount (INR)
count        1.046198e+06     1.048567e+06             1.048567e+06
mean         1.154035e+05     1.570875e+05             1.574335e+03
std          8.464854e+05     5.126185e+04             6.574743e+03
min          0.000000e+00     0.000000e+00             0.000000e+00
25%          4.721760e+03     1.240300e+05             1.610000e+02
50%          1.679218e+04     1.642260e+05             4.590300e+02
75%          5.765736e+04     2.000100e+05             1.200000e+03
max          1.150355e+08     2.359590e+05             1.560035e+06

In [ ]:
df.select_dtypes(include='object').describe()

,TransactionID,CustomerID,CustomerDOB,CustGender,CustLocation,TransactionDate
count,1048567,1048567,1045170,1047467,1048416,1048567
unique,1048567,884265,17254,3,9355,55
top,T1048567,C3226689,1/1/1800,M,MUMBAI,7/8/16
freq,1,6,57339,765530,103595,27261

In [ ]:
#Renameing the Transaction amount coklumn
df.rename(columns={'TransactionAmount (INR)':'TransactionAmount'},inplace=True)

In [ ]:
df1 = df.copy()

In [ ]:
#handle date columns
df1['TransactionDate'] = pd.to_datetime(df1['TransactionDate'])
df1['CustomerDOB'] = pd.to_datetime(df1['CustomerDOB'])

In [ ]:
df1['TransactionDate']

0         2016-02-08
1         2016-02-08
2         2016-02-08
3         2016-02-08
4         2016-02-08
             ...
1048562   2016-09-18
1048563   2016-09-18
1048564   2016-09-18
1048565   2016-09-18
1048566   2016-09-18
Name: TransactionDate, Length: 1048567, dtype: datetime64[ns]

In [ ]:
df1['TransactionTime'] = df1['TransactionTime'].astype(str).str.zfill(6)
df1['TransactionTime'] = pd.to_datetime(df1['TransactionTime'],format='%H%M%S').dt.time
df1['TransactionTime']

0          14:32:07
1          14:18:58
2          14:27:12
3          14:27:14
4          18:11:56
             ...
1048562    18:48:24
1048563    18:37:34
1048564    18:33:13
1048565    18:47:06
1048566    18:12:22
Name: TransactionTime, Length: 1048567, dtype: object

In [ ]:
df1.describe()

,CustomerDOB,CustAccountBalance,TransactionDate,TransactionAmount
count,1045170,1.046198e+06,1048567,1.048567e+06
mean,1985-05-09 04:31:20.320330688,1.154035e+05,2016-07-25 19:17:20.973825024,1.574335e+03
min,1800-01-01 00:00:00,0.000000e+00,2016-01-08 00:00:00,0.000000e+00
25%,1983-11-30 00:00:00,4.721760e+03,2016-06-09 00:00:00,1.610000e+02
50%,1988-12-11 00:00:00,1.679218e+04,2016-08-20 00:00:00,4.590300e+02
75%,1992-08-22 00:00:00,5.765736e+04,2016-09-09 00:00:00,1.200000e+03
max,2074-12-31 00:00:00,1.150355e+08,2016-12-09 00:00:00,1.560035e+06
std,NaN,8.464854e+05,NaN,6.574743e+03

In [ ]:
df1.select_dtypes(include='object').describe()

       TransactionID CustomerID CustGender CustLocation TransactionTime
count        1048567    1048567    1047467      1048416         1048567
unique       1048567     884265          3         9355           81918
top         T1048567   C3226689          M       MUMBAI        19:50:02
freq               1          6     765530       103595              46

* Around 1 lakh customers are from Mumbai
* Male is the predominant gender
* Customers born in 1800 cannot be alive today to make transactions in 2016
* Similarly, customers can't be born in the year 2073

In [ ]:
#find out customer's age
from datetime import datetime

today = datetime.today().year
df1['Age'] = today - df1['CustomerDOB'].dt.year

In [ ]:
df1.sample(10)

,TransactionID,CustomerID,CustomerDOB,CustGender,CustLocation,CustAccountBalance,TransactionDate,TransactionTime,TransactionAmount,Age
905842,T905843,C3140940,1985-03-06,M,PUNE,10734.89,2016-12-09,14:18:03,700.00,40.0
920584,T920585,C2459820,1985-06-27,M,NOIDA,20536.89,2016-12-09,21:29:48,615.00,40.0
810456,T810457,C8399067,1990-01-25,M,ROHTAS,10809.87,2016-04-09,21:21:12,240.00,35.0
448051,T448052,C7010325,1978-01-14,M,NEW DELHI,59403.32,2016-08-16,16:38:14,1048.00,47.0
821186,T821187,C2598382,1983-01-12,F,EAST NALLOSAPARE E THANE,438.62,2016-04-09,16:56:01,5345.65,42.0
360548,T360549,C1742468,1985-01-22,M,GURGAON,35175.62,2016-08-14,17:32:13,362.00,40.0
423706,T423707,C2718964,1980-07-09,M,MOMBASA,4875052.46,2016-08-17,12:31:04,3273.50,45.0
439910,T439911,C8738783,1977-01-05,M,DELHI,7325.23,2016-08-16,11:07:42,1000.00,48.0
746582,T746583,C5324789,1988-05-06,M,CHENNAI,13252.29,2016-01-09,22:06:03,347.00,37.0
914303,T914304,C1631730,1990-02-15,M,SALEM,11514.62,2016-12-09,18:18:11,65.00,35.0

In [ ]:
#We're only keeping customers aged between 18 and 90
df2 = df1[df1['Age'].between(18,90)]

In [ ]:
#Check out how many transactions had invalid customer ages
print(df1.shape)
print(df2.shape)

(1048567, 10)
(882440, 10)

In [ ]:
#Check if null values exist in the filtered dataframe
df2.isna().sum()

TransactionID            0
CustomerID               0
CustomerDOB              0
CustGender              13
CustLocation           111
CustAccountBalance    1969
TransactionDate          0
TransactionTime          0
TransactionAmount        0
Age                      0
dtype: int64

In [ ]:
#We choose to drop those null values, since they won't affect the data that much
df3 = df2.dropna()
print(df3.shape)

(880347, 10)

In [ ]:
#Check out the unique rows by transaction IDs
df3['TransactionID'].nunique()

880347

In [ ]:
#Check out the unique rows by customer IDs
df3['CustomerID'].nunique()

761834

In [ ]:
#Only keep rows where customer IDs are unique, drop the rest
df4 = df3.drop_duplicates(subset='CustomerID')
df4.shape

(761834, 10)

In [ ]:
#Drop unnecessary columns
df5 = df4.drop(['CustomerID','TransactionID','CustomerDOB'],axis=1)
df5.sample(3)

,CustGender,CustLocation,CustAccountBalance,TransactionDate,TransactionTime,TransactionAmount,Age
124116,M,NEW DELHI,82914.91,2016-06-08,16:51:57,1100.0,49.0
364690,M,AMRITSAR,66636.77,2016-08-14,20:32:50,55.0,32.0
734865,M,DELHI,87644.45,2016-02-09,12:24:13,5096.0,33.0

In [ ]:
#Change the data type of 'Age' column from float to integer
df5['Age'] = df5['Age'].astype('int64')

In [ ]:
df5.select_dtypes(include=object).describe()

       CustGender CustLocation TransactionTime
count      761834       761834          761834
unique          2         7269           79600
top             M       MUMBAI        19:57:08
freq       550527        74796              39

Notice that there is clear imbalance in data since most individuals are from the male population.

In [ ]:
#Check out the count of individuals in each Gender
df5['CustGender'].value_counts()

CustGender
M    550527
F    211307
Name: count, dtype: int64

In [ ]:
#Check out % of individuals in each Gender
df5['CustGender'].value_counts(normalize=True)*100

CustGender
M    72.26338
F    27.73662
Name: proportion, dtype: float64

In [ ]:
#Show the number of population in each location
value_counts = df5['CustLocation'].value_counts()
value_counts_df = value_counts.reset_index()
value_counts_df.columns = ['CustLocation', 'ValueCounts']
value_counts_df

          CustLocation  ValueCounts
0               MUMBAI        74796
1            BANGALORE        61269
2            NEW DELHI        57230
3              GURGAON        54544
4                DELHI        52379
...                ...          ...
7264     KANGRA KANGRA            1
7265      TAL BHIWANDI            1
7266  MYSORE BANGALORE            1
7267          DEVAGHAR            1
7268         TANJAVORE            1

[7269 rows x 2 columns]

In [ ]:
#Locations with most frequent transactions
locations = value_counts_df[value_counts_df['ValueCounts'].between(1000,74796)]
locations_arr = list(locations['CustLocation'])
locations_arr

['MUMBAI',
 'BANGALORE',
 'NEW DELHI',
 'GURGAON',
 'DELHI',
 'NOIDA',
 'CHENNAI',
 'PUNE',
 'HYDERABAD',
 'THANE',
 'KOLKATA',
 'GHAZIABAD',
 'NAVI MUMBAI',
 'AHMEDABAD',
 'FARIDABAD',
 'JAIPUR',
 'CHANDIGARH',
 'LUCKNOW',
 'MOHALI',
 'SURAT',
 'NASHIK',
 'LUDHIANA',
 'VISAKHAPATNAM',
 'DEHRADUN',
 'INDORE',
 'KANPUR',
 'VADODARA',
 'AMRITSAR',
 'MEERUT',
 'NAGPUR',
 'AGRA',
 'GREATER NOIDA',
 'COIMBATORE',
 'RANGA REDDY',
 'AURANGABAD',
 'PANCHKULA',
 'GUNTUR',
 'GUWAHATI',
 'JALANDHAR',
 'BHOPAL',
 'PATNA',
 'UDAIPUR',
 'REWARI',
 'RANCHI',
 'BENGALURU',
 'HOWRAH',
 'PATIALA',
 'ALWAR',
 'NORTH 24 PARGANAS',
 'ERNAKULAM',
 'SONIPAT',
 'SECUNDERABAD',
 'ALLAHABAD',
 'PANIPAT',
 'BAMBOLIM',
 'SILIGURI',
 'ZIRAKPUR',
 'KOLHAPUR',
 'RAJKOT',
 'BAREILLY',
 'KANGRA',
 'ALIGARH',
 'RAIPUR',
 'JAMSHEDPUR',
 'KARNAL',
 'WARANGAL',
 'AMBALA',
 'MANGALORE',
 'KHARAR',
 'KOTTAYAM',
 'SAS NAGAR',
 'SAHARANPUR',
 'HOSUR',
 'MORADABAD']

In [ ]:
#Considering only those transactions in popular locations

df6 = df5[df5['CustLocation'].isin(locations_arr)]
print(df5.shape)
print(df6.shape)

(761834, 7)
(572822, 7)